# .goreleaser.yaml
project_name: template-go
builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
    main: ./
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -extldflags '-static'
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commitSHA={{.FullCommit}}
      - -X main.buildDate={{.Date}}
brews:
  - name: "template-go"
    homepage: "https://github.com/vonglasow/template-go"
    description: "Template"
    license: "GPL3"
    url_template: "https://github.com/vonglasow/template-go/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    repository:
      owner: vonglasow
      name: homebrew-go-template
      branch: main
